#Minecraft server properties
#Thu Mar 19 20:32:23 UTC 2026
enable-jmx-monitoring=false
level-seed=
rcon.port=25575
enable-command-block=true
gamemode=0
enable-query=false
generator-settings={}
enforce-secure-profile=false
level-name=world
motd=\u00A7fThis Server is powered by \u00A77G\u00A7fi\u00A77t\u00A7fh\u00A77u\u00A7fb\u00A77\!
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=1
network-compression-threshold=-1
max-tick-time=60000
require-resource-pack=false
max-players=200
use-native-transport=true
enable-status=true
online-mode=false
allow-flight=false
initial-disabled-packs=
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
resource-pack-prompt=
server-ip=
allow-nether=false
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
server-name=Unknown Server
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=5
player-idle-timeout=0
rcon.password=
announce-player-achievements=false
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
previews-chat=false
spawn-npcs=false
spawn-animals=false
snooper-enabled=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=flat
text-filtering-config=
spawn-monsters=false
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984
resource-pack-hash=
